Add --autostash to git updatepr (#50)
If you have other changes this can fail with:

```
$ git updatepr HEAD~1
error: cannot rebase: You have unstaged changes.
error: Please commit or stash them.
```

I never saw this because I globally have `rebase.autostash true` in my
gitconfig.